import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/lib/auth-context";
import { Sidebar } from "@/components/Sidebar";
import { Toaster } from "@/components/ui/sonner";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { BellIcon } from "@heroicons/react/24/outline";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#FFFFFF]`}>
        <AuthProvider>
          <div className="flex min-h-screen">
            <Sidebar />
            <div className="flex-1 flex flex-col min-h-screen">
              <header className="flex items-center justify-between px-8 py-4 bg-transparent">
                <div className="flex-1 max-w-xl">
                  <Input placeholder="Search or type a command" className="rounded-xl bg-white/80 border border-gray-200 shadow-sm focus:ring-2 focus:ring-purple-200" />
                </div>
                <div className="flex items-center gap-6 ml-8">
                  <Button variant="ghost" size="icon" className="rounded-full hover:bg-purple-100">
                    <BellIcon className="w-6 h-6 text-gray-400" />
                  </Button>
                  <div className="w-10 h-10 rounded-full bg-gradient-to-tr from-purple-300 to-pink-200 border-2 border-white shadow-inner overflow-hidden">
                    <span className="block w-full h-full" />
                  </div>
                </div>
              </header>
              <main className="flex-1 px-12 md:px-6 sm:px-4">
                {children}
              </main>
            </div>
          </div>
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
